"""Edit fields of student table

Revision ID: 2563567e55a3
Revises: 384dbfb21a58
Create Date: 2024-11-12 14:46:28.824414

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2563567e55a3'
down_revision = '384dbfb21a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('student', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('student', 'json_data',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'json_data',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
