"""Add column last_name to User model 555

Revision ID: 5d7e2dc76f22
Revises: 9add8cd3eb99
Create Date: 2024-11-05 13:27:47.526703

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5d7e2dc76f22'
down_revision = '9add8cd3eb99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
