"""Add student

Revision ID: 7c3d3f2c6211
Revises: 5d7e2dc76f22
Create Date: 2024-11-11 22:52:12.677294

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7c3d3f2c6211'
down_revision = '5d7e2dc76f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'unit')
    # ### end Alembic commands ###
