"""Add table Product

Revision ID: 9070ef6ce07d
Revises: f69233934d4b
Create Date: 2024-10-11 13:26:56.098458

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9070ef6ce07d'
down_revision = 'f69233934d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
