"""Update entity base

Revision ID: 9add8cd3eb99
Revises: 06deb63d3158
Create Date: 2024-10-11 14:47:51.989358

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9add8cd3eb99'
down_revision = '06deb63d3158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('category', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'category', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'category', 'user', ['updated_by'], ['id'])
    op.add_column('product', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('product', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'product', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'product', 'user', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'updated_by')
    op.drop_column('product', 'created_by')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'updated_by')
    op.drop_column('category', 'created_by')
    # ### end Alembic commands ###
