"""Check all table

Revision ID: a59cf50224e3
Revises: edf97f5980d5
Create Date: 2024-10-11 14:35:28.965501

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a59cf50224e3'
down_revision = 'edf97f5980d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
