"""Add table Product FK

Revision ID: edf97f5980d5
Revises: 89bc7631137b
Create Date: 2024-10-11 13:40:25.949324

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'edf97f5980d5'
down_revision = '89bc7631137b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('product', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('product', sa.Column('category_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'category_id')
    op.drop_column('product', 'description')
    op.drop_column('product', 'name')
    # ### end Alembic commands ###
